import Providers from "./providers";
import "./globals.css";
import { Geist, Geist_Mono } from "next/font/google";
import { ToastContainer, toast } from 'react-toastify';
import ClientWrapper from "@/components/ClientWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Prepare Your self",
  description: "Generated by Aman Singh",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Providers>
          {/* <ClientWrapper > */}
            {children}
          {/* </ClientWrapper > */}
          <div id="modal-root"></div>
        </Providers>
        <ToastContainer />
      </body>
    </html>
  );
}
